//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Astronaut
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Astronaut()
        {
            this.allergyAstr = new HashSet<allergyAstr>();
            this.caffeineConsumption = new HashSet<caffeineConsumption>();
            this.chronicDiseaseAstr = new HashSet<chronicDiseaseAstr>();
            this.Exercise = new HashSet<Exercise>();
            this.Meals = new HashSet<Meals>();
            this.MedAstr = new HashSet<MedAstr>();
            this.Sleep = new HashSet<Sleep>();
        }
    
        public int idAstr { get; set; }
        public Nullable<int> idTrip { get; set; }
        public string passw { get; set; }
        public string name { get; set; }
        public string surname { get; set; }
        public Nullable<System.DateTime> birth { get; set; }
        public string gender { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> height { get; set; }
        public string nationality { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<allergyAstr> allergyAstr { get; set; }
        public virtual Trip Trip { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<caffeineConsumption> caffeineConsumption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chronicDiseaseAstr> chronicDiseaseAstr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exercise> Exercise { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meals> Meals { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedAstr> MedAstr { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sleep> Sleep { get; set; }

        public Astronaut(int idAstr, int idTrip, string name, string surname, DateTime birth, string gender, double weight, double height, string nationality)
        {
            this.idAstr = idAstr;
            this.idTrip = idTrip;
            this.name = name;
            this.surname = surname;
            this.birth = birth;
            this.gender = gender;
            this.weight = weight;
            this.height = height;
            this.nationality = nationality;
        }
    }
}
