//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class caffeineConsumption
    {
        public int idCafCon { get; set; }
        public Nullable<int> idAstr { get; set; }
        public Nullable<System.DateTime> timeCons { get; set; }
    
        public virtual Astronaut Astronaut { get; set; }

        public caffeineConsumption()
        {
        }

        public caffeineConsumption(int idAstr, DateTime timeCons)
        {
            this.idAstr = idAstr;
            this.timeCons = timeCons;
        }
    }
}
