//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Meals
    {
        public int idMeal { get; set; }
        public Nullable<int> idAstr { get; set; }
        public Nullable<int> idFood { get; set; }
        public Nullable<System.DateTime> mealTime { get; set; }
        public string mealType { get; set; }
    
        public virtual Astronaut Astronaut { get; set; }
        public virtual Food Food { get; set; }

        public Meals() {        }

        public Meals(int idAstr, int idFood, DateTime mealTime, string mealType)
        {
            this.idAstr = idAstr;
            this.idFood = idFood;
            this.mealTime = mealTime;
            this.mealType = mealType;
        }
    }
}
