//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedChrDis
    {
        public int idMedCD { get; set; }
        public Nullable<int> idMed { get; set; }
        public Nullable<int> idCD { get; set; }
    
        public virtual ChronicDiseases ChronicDiseases { get; set; }
        public virtual Medicines Medicines { get; set; }
    }
}
