//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpaceApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MorfeoAppEntities : DbContext
    {
        public MorfeoAppEntities()
            : base("name=MorfeoAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allergies> Allergies { get; set; }
        public virtual DbSet<allergyAstr> allergyAstr { get; set; }
        public virtual DbSet<Astronaut> Astronaut { get; set; }
        public virtual DbSet<caffeineConsumption> caffeineConsumption { get; set; }
        public virtual DbSet<chronicDiseaseAstr> chronicDiseaseAstr { get; set; }
        public virtual DbSet<ChronicDiseases> ChronicDiseases { get; set; }
        public virtual DbSet<Equipment> Equipment { get; set; }
        public virtual DbSet<Exercise> Exercise { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<Meals> Meals { get; set; }
        public virtual DbSet<MedAstr> MedAstr { get; set; }
        public virtual DbSet<MedChrDis> MedChrDis { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<Sleep> Sleep { get; set; }
        public virtual DbSet<Trip> Trip { get; set; }
    }
}
